#!/usr/bin/env node
// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Trusted candidate classification. This runs from the base revision and uses
// provider metadata only; proposed pull-request code is not checked out here.

import { appendFileSync, readFileSync } from "node:fs"
import { loadAdapter } from "../../runtime/adapter-loader.mjs"

const ENTRYPOINTS = {"source":"./pipelines/code-scanning-remediation/adapters/source.mjs","workItem":"./pipelines/code-scanning-remediation/adapters/work-item.mjs","execution":"./pipelines/code-scanning-remediation/adapters/execution.mjs","delivery":"./pipelines/code-scanning-remediation/adapters/delivery.mjs","validation":"./pipelines/code-scanning-remediation/adapters/validation.mjs"}
const PIPELINE_ID = "code-scanning-remediation"
const BASE_BRANCH = "main".replace(/^refs\/heads\//, "")
const REPOSITORY = process.env.GITHUB_REPOSITORY || ""
// The pull request's actual author is not always the same login as the work
// item's assignee: GitHub's Copilot coding agent, for example, is assigned as
// "copilot-swe-agent[bot]" but opens pull requests as a different app login.
// agentAuthorLogins is authoritative when declared; agentAssignees remains a
// fallback for delegated agents (or plain-issue human assignees) that do open
// their own pull requests under the assigned login.
const ALLOWED_AUTHORS = new Set(
  [
    ...["copilot-swe-agent[bot]"],
    ...["Copilot"],
  ].map((value) => value.toLowerCase()),
)

function output(name, value) {
  const path = process.env.GITHUB_OUTPUT
  if (path) appendFileSync(path, `${name}=${value}\n`)
  console.log(`${name}=${value}`)
}

function eventPullRequest() {
  const path = process.env.GITHUB_EVENT_PATH
  if (!path) return null
  try {
    const payload = JSON.parse(readFileSync(path, "utf8"))
    return payload && payload.pull_request || null
  } catch {
    return null
  }
}

async function main() {
  const pullRequest = eventPullRequest()
  const body = String(pullRequest && pullRequest.body || "")
  const author = String(pullRequest && pullRequest.user && pullRequest.user.login || "").toLowerCase()
  const baseRef = String(pullRequest && pullRequest.base && pullRequest.base.ref || "")
  const headRepository = String(
    pullRequest && pullRequest.head && pullRequest.head.repo && pullRequest.head.repo.full_name || "",
  )
  const candidate =
    ALLOWED_AUTHORS.has(author) && baseRef === BASE_BRANCH && headRepository === REPOSITORY
  if (!candidate) {
    output("candidate", "false")
    output("trusted", "false")
    return
  }

  const delivery = await loadAdapter("delivery", ENTRYPOINTS.delivery)
  if (delivery === null) throw new Error("candidate classification requires a delivery adapter")

  const change = await delivery.locateChange()
  if (change && change.pipeline && change.pipeline !== PIPELINE_ID) {
    throw new Error(`configured agent pull request belongs to pipeline '${change.pipeline}'`)
  }
  if (change) {
    output("candidate", "true")
    output("trusted", change.workItemTrusted === true ? "true" : "false")
    return
  }

  const hasRoutingHint =
    body.includes("<!-- agentic-fingerprint:") ||
    body.includes("<!-- agentic-pipeline:") ||
    /\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#\d+\b/i.test(body)
  if (hasRoutingHint) {
    output("candidate", "false")
    output("trusted", "false")
    return
  }

  const previous =
    typeof delivery.previousEvidenceCandidate === "function"
      ? await delivery.previousEvidenceCandidate()
      : null
  output("candidate", previous === false ? "false" : "true")
  output("trusted", "false")
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
