#!/usr/bin/env node
// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Unprivileged repository checks. The host runs this from the trusted base
// checkout against the proposed change checkout, without provider credentials.

import { execFile } from "node:child_process"

const COMMANDS = ["echo"]
const TIMEOUT_SECONDS = 900

function run(command) {
  const env = Object.fromEntries(
    ["PATH", "HOME", "TMPDIR", "TEMP", "TMP", "LANG", "LC_ALL", "CI"].flatMap((name) =>
      process.env[name] === undefined ? [] : [[name, process.env[name]]],
    ),
  )

  return new Promise((resolve) => {
    execFile(
      "/bin/sh",
      ["-c", command],
      {
        cwd: process.env.AGENTIC_REPOSITORY_PATH || process.cwd(),
        env,
        timeout: TIMEOUT_SECONDS * 1000,
        encoding: "utf8",
      },
      (error, stdout, stderr) => {
        resolve({
          ok: !error,
          detail: error ? String(stderr || stdout || error.message).trim().split("\n").pop() : "exit 0",
        })
      },
    )
  })
}

async function main() {
  if (COMMANDS.length === 0) {
    console.log("No repository checks are configured.")
    return
  }

  let failed = false
  for (const command of COMMANDS) {
    const result = await run(command)
    console.log(`${result.ok ? "PASS" : "FAIL"} ${command}: ${result.detail}`)
    if (!result.ok) failed = true
  }

  if (failed) process.exitCode = 1
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
