#!/usr/bin/env node
// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Validation entrypoint: locate the change, assert machine-checked facts,
// derive a decision and confidence level, then post it for the human reviewer.

import { loadAdapter } from "../../runtime/adapter-loader.mjs"

const ENTRYPOINTS = {"source":"./pipelines/code-scanning-remediation/adapters/source.mjs","workItem":"./pipelines/code-scanning-remediation/adapters/work-item.mjs","execution":"./pipelines/code-scanning-remediation/adapters/execution.mjs","delivery":"./pipelines/code-scanning-remediation/adapters/delivery.mjs","validation":"./pipelines/code-scanning-remediation/adapters/validation.mjs"}
const PIPELINE_ID = "code-scanning-remediation"

async function main() {
  const validation = await loadAdapter("validation", ENTRYPOINTS.validation)
  if (validation === null) {
    console.log("No validation adapter is installed; nothing to assert.")
    return
  }

  const delivery = await loadAdapter("delivery", ENTRYPOINTS.delivery)
  if (delivery === null) throw new Error("validation requires a delivery adapter to locate the change")

  const change = await delivery.locateChange()
  if (change === null) {
    if (process.env.AGENTIC_CANDIDATE === "true") {
      throw new Error("candidate pull request is not linked to a trusted work item")
    }
    console.log("No reviewable change was found for this event.")
    return
  }

  if (change.pipeline && change.pipeline !== PIPELINE_ID) {
    throw new Error(`candidate pull request belongs to pipeline '${change.pipeline}', not '${PIPELINE_ID}'`)
  }

  const result = await validation.assess(change)
  console.log(result.body)

  if (process.env.AGENTIC_DRY_RUN !== "true") await delivery.comment(change, result.body)

  if (result.blocking) {
    console.error(`Evidence blocked by: ${result.blockers.join(", ")}`)
    process.exitCode = 1
  }
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
