#!/usr/bin/env node
// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Intake entrypoint: source -> work request -> policy -> work item.
// A seam left as handoff simply has no module, and the pipeline stops there.

import { assertWorkRequest } from "../../runtime/work-request.mjs"
import { loadAdapter } from "../../runtime/adapter-loader.mjs"

const DRY_RUN = process.argv.includes("--dry-run") || process.env.AGENTIC_DRY_RUN === "true"

const ENTRYPOINTS = {"source":"./pipelines/code-scanning-remediation/adapters/source.mjs","workItem":"./pipelines/code-scanning-remediation/adapters/work-item.mjs","execution":"./pipelines/code-scanning-remediation/adapters/execution.mjs","delivery":"./pipelines/code-scanning-remediation/adapters/delivery.mjs","validation":"./pipelines/code-scanning-remediation/adapters/validation.mjs"}
const PIPELINE_ID = "code-scanning-remediation"

async function main() {
  const source = await loadAdapter("source", ENTRYPOINTS.source)
  if (source === null) throw new Error("no source adapter is installed; nothing to discover")

  const workItem = await loadAdapter("workItem", ENTRYPOINTS.workItem)
  const execution = await loadAdapter("execution", ENTRYPOINTS.execution)

  const requests = (await source.discover())
    .map((request) => ({ ...request, pipeline: PIPELINE_ID }))
    .map(assertWorkRequest)
  console.log(`Found ${requests.length} eligible work request(s)`)

  if (DRY_RUN) {
    console.log("--- normalized work requests ---")
    console.log(JSON.stringify(requests, null, 2))
    return
  }

  if (workItem === null) {
    console.log("No work-item adapter is installed; stopping after discovery.")
    return
  }

  if (
    typeof workItem.MAX_OPEN_WORK_REQUESTS !== "number" ||
    !Number.isSafeInteger(workItem.MAX_OPEN_WORK_REQUESTS) ||
    workItem.MAX_OPEN_WORK_REQUESTS < 1
  ) {
    throw new Error("work-item adapter MAX_OPEN_WORK_REQUESTS must be a positive integer")
  }

  const sources = [...new Set(requests.map((request) => request.source))]
  const existing = await workItem.findExisting({ sources })
  let open = existing.openCount
  console.log(`${existing.fingerprints.size} known fingerprint(s), ${open} open work request(s)`)

  for (const request of requests) {
    if (existing.fingerprints.has(request.fingerprint)) {
      console.log(`${request.reference || request.sourceId}: work request already exists, skipping`)
      continue
    }

    // Review capacity, not generation capacity, is the binding constraint.
    if (open >= workItem.MAX_OPEN_WORK_REQUESTS) {
      console.log(
        `Reached maxOpenWorkRequests (${workItem.MAX_OPEN_WORK_REQUESTS}); stopping before ${request.reference || request.sourceId}`
      )
      break
    }

    const directive = execution === null ? null : execution.describe(request)
    const created = await workItem.create(request, directive)
    open += 1
    console.log(`${request.reference || request.sourceId}: dispatched as ${created.url}`)
  }
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
