// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.

/**
 * Load a bound seam module. A null specifier is an intentional handoff; any
 * import failure for a declared adapter is a real installation error. The
 * export check keeps a new adapter from silently becoming a partial pipeline.
 */
const REQUIRED_EXPORTS = {
  source: ["discover", "reverify"],
  workItem: ["findExisting", "create"],
  execution: ["describe"],
  delivery: ["locateChange", "changedPaths", "comment"],
  validation: ["assess"],
}

export async function loadAdapter(seam, specifier) {
  if (specifier === null) return null

  try {
    const runtimeRelative = specifier.startsWith("./") ? `../${specifier.slice(2)}` : specifier
    const module = await import(new URL(runtimeRelative, import.meta.url).href)
    const missing = (REQUIRED_EXPORTS[seam] || []).filter(
      (name) => typeof module[name] !== "function",
    )
    if (missing.length > 0) {
      throw new Error(`missing required export(s): ${missing.join(", ")}`)
    }
    return module
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error)
    throw new Error(`failed to load ${seam} adapter '${specifier}': ${detail}`, { cause: error })
  }
}
