// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// The cross-adapter contract. Mirrors schema/work-request.schema.json; the
// conformance test validates real adapter output against that schema.

export const FINGERPRINT_TAG = "agentic-fingerprint"
export const CORRELATION_TAG = "agentic-correlation"
export const PIPELINE_TAG = "agentic-pipeline"

const REQUIRED_STRINGS = [
  "source",
  "sourceId",
  "url",
  "fingerprint",
  "workType",
  "repository",
  "baseBranch",
  "title",
  "instructions",
]
const WORK_TYPES = new Set([
  "security-remediation",
  "quality-remediation",
  "dependency-update",
  "ci-failure",
  "incident",
  "feature",
])

/** A fingerprint is namespaced by its source so two adapters cannot collide. */
export function fingerprint(source, repository, id) {
  return `${source}:${repository}:${id}`
}

export function assertWorkRequest(request) {
  if (!request || typeof request !== "object" || Array.isArray(request)) {
    throw new Error("work request must be an object")
  }

  const missing = REQUIRED_STRINGS.filter(
    (field) => typeof request[field] !== "string" || request[field].length === 0,
  )
  if (missing.length > 0) {
    throw new Error(`work request is missing required string field(s): ${missing.join(", ")}`)
  }
  if (!WORK_TYPES.has(request.workType)) {
    throw new Error(`work request has invalid workType '${String(request.workType)}'`)
  }
  if (!/^[a-z0-9][a-z0-9-]*$/.test(request.source)) {
    throw new Error(`work request has invalid source '${request.source}'`)
  }
  if (typeof request.description !== "string") {
    throw new Error("work request description must be a string")
  }
  if (!/^[a-z0-9][a-z0-9-]*:.+$/.test(request.fingerprint)) {
    throw new Error(`work request has invalid fingerprint '${request.fingerprint}'`)
  }
  if (request.pipeline !== undefined && !/^[a-z0-9][a-z0-9-]*$/.test(request.pipeline)) {
    throw new Error(`work request has invalid pipeline '${request.pipeline}'`)
  }
  if (!Array.isArray(request.labels) || request.labels.some((label) => typeof label !== "string")) {
    throw new Error("work request labels must be an array of strings")
  }
  return request
}

export function readMarker(body, tag) {
  const match = new RegExp(`<!-- ${tag}: ([^>]+) -->`).exec(body || "")
  return match ? match[1].trim() : ""
}

export function writeMarker(tag, value) {
  return `<!-- ${tag}: ${value} -->`
}
