// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Confidence is a summary of checked facts, never a claim of correctness, and
// never prose produced by a model. If an assertion could not be evaluated it is
// reported as `skip` and lowers confidence rather than being quietly dropped.

export const PROTECTED_PATHS = [".github/workflows/",".agentic/","scripts/agentic/"]
export const REQUIRE_TEST_FOR_TOUCHED_CODE = false

export function assertion(id, title, status, detail = "") {
  if (!["pass", "fail", "skip"].includes(status)) {
    throw new Error(`assertion '${id}' has an invalid status: ${status}`)
  }
  return { id, title, status, detail: String(detail || "") }
}

export function protectedPathViolations(paths, protectedPaths = PROTECTED_PATHS) {
  return paths.filter((path) => protectedPaths.some((prefix) => path.startsWith(prefix)))
}

export function looksLikeTest(path) {
  return /(^|\/)(tests?|__tests__|spec)\//.test(path) || /\.(test|spec)\.[a-z]+$/.test(path)
}

/**
 * Deliberately blunt: any failure caps confidence at low, and anything
 * unevaluated caps it at medium. A reviewer can trust the level without
 * reading the whole table.
 */
export function confidence(assertions) {
  const failed = assertions.filter((item) => item.status === "fail")
  const skipped = assertions.filter((item) => item.status === "skip")

  if (failed.length > 0) {
    return { level: "low", reason: `${failed.length} check(s) failed` }
  }
  if (skipped.length > 0) {
    return { level: "medium", reason: `${skipped.length} check(s) could not be evaluated` }
  }
  return { level: "high", reason: "every check passed" }
}

/** Every failed assertion blocks merge eligibility in the MVP. */
export function decision(assertions) {
  const blockers = assertions.filter((item) => item.status === "fail")
  return blockers.length > 0
    ? { status: "blocked", blockers: blockers.map((item) => item.id) }
    : { status: "human-review", blockers: [] }
}

const ICON = { pass: "PASS", fail: "FAIL", skip: "SKIP" }

export function formatComment({ assertions, confidence: level, fingerprint, decision: outcome }) {
  const rows = assertions.map((item) =>
    `| ${ICON[item.status]} | ${item.title} | ${item.detail.replace(/\|/g, "/")} |`
  )

  // Blank lines are load-bearing here: without them the table does not render.
  const lines = [
    "## Agentic evidence",
    "",
    `**Decision: ${outcome.status}**`,
    outcome.blockers.length > 0 ? `**Blocking checks: ${outcome.blockers.join(", ")}**` : "",
    "",
    `**Confidence: ${level.level}** — ${level.reason}`,
    "",
    "| Result | Check | Detail |",
    "| ------ | ----- | ------ |",
    ...rows,
    "",
    "Confidence summarises the checks above. It is not a guarantee; a human still reviews and merges.",
  ]

  if (fingerprint) lines.push("", `<!-- agentic-evidence-for: ${fingerprint} -->`)
  return lines.join("\n")
}
