// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Provider-neutral transport. Every adapter builds on this, which is why it
// carries no authentication, no host and no API shape.

export const MAX_RETRIES = 3
const DEBUG = false

export function log(message) {
  if (DEBUG) console.log(message)
}

export function requireEnv(name) {
  const value = process.env[name]
  if (!value) throw new Error(`${name} is required`)
  return value
}

/**
 * Retries only what is worth retrying: transport failures, 5xx and 429. A 4xx
 * is a contract error and is returned to the caller immediately.
 */
export async function withRetry(operation, maxRetries = MAX_RETRIES) {
  let lastError

  for (let attempt = 1; attempt <= maxRetries; attempt += 1) {
    try {
      const response = await operation()
      if (response.status < 500 && response.status !== 429) return response
      lastError = new Error(`HTTP ${response.status}`)
      if (attempt === maxRetries) return response
    } catch (error) {
      lastError = error
      if (attempt === maxRetries) throw error
    }

    const delay = 500 * 2 ** (attempt - 1)
    log(`retrying in ${delay}ms (${lastError.message})`)
    await new Promise((resolve) => setTimeout(resolve, delay))
  }

  throw lastError
}

export function createClient({ baseUrl, headers = {}, maxRetries = MAX_RETRIES }) {
  const request = (path, options = {}) =>
    withRetry(
      () =>
        fetch(`${baseUrl}${path}`, {
          ...options,
          headers: { ...headers, ...(options.headers || {}) },
        }),
      maxRetries
    )

  return {
    request,
    async json(path, options = {}) {
      const response = await request(path, options)
      if (!response.ok) {
        throw new Error(`${options.method || "GET"} ${path} failed: ${response.status} ${await response.text()}`)
      }
      return response.json()
    },
  }
}
