// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Eligibility is deliberately explicit and deny-by-default: a finding that does
// not match every configured filter is left for a human.

export const POLICY = {
  securitySeverities: ["critical","high"],
  includeNonSecurityAlerts: false,
  ruleSeverities: [],
  tools: [],
  ruleAllowList: [],
  ruleDenyList: [],
  pathIncludes: [],
  pathExcludes: [],
  excludeClassifications: ["test","generated","library"],
}

/**
 * candidate: { ruleId, tool, securitySeverity, ruleSeverity, path, classifications }
 * Returns null when eligible, or a string reason when it is not.
 */
export function ineligibleReason(candidate, policy = POLICY) {
  const ruleId = candidate.ruleId || ""
  const path = candidate.path || ""
  const classifications = candidate.classifications || []

  if (policy.ruleDenyList.includes(ruleId)) return `rule ${ruleId} is denied`
  if (policy.ruleAllowList.length > 0 && !policy.ruleAllowList.includes(ruleId)) {
    return `rule ${ruleId} is not in the allow list`
  }
  if (policy.tools.length > 0 && !policy.tools.includes(candidate.tool || "")) {
    return `tool ${candidate.tool} is not in scope`
  }

  if (candidate.securitySeverity) {
    if (!policy.securitySeverities.includes(candidate.securitySeverity)) {
      return `security severity ${candidate.securitySeverity} is not in scope`
    }
  } else {
    if (!policy.includeNonSecurityAlerts) return "finding carries no security severity"
    if (!policy.ruleSeverities.includes(candidate.ruleSeverity || "")) {
      return `rule severity ${candidate.ruleSeverity} is not in scope`
    }
  }

  const excluded = classifications.filter((item) => policy.excludeClassifications.includes(item))
  if (excluded.length > 0) return `classified as ${excluded.join(", ")}`

  if (policy.pathIncludes.length > 0 && !policy.pathIncludes.some((prefix) => path.startsWith(prefix))) {
    return `${path} is outside the included paths`
  }
  if (policy.pathExcludes.some((prefix) => prefix !== "" && path.startsWith(prefix))) {
    return `${path} is excluded`
  }

  return null
}

export function isEligible(candidate, policy = POLICY) {
  return ineligibleReason(candidate, policy) === null
}
