// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Delivery seam for GitHub pull requests.
//
// The pull request is produced by the execution seam, so this adapter only
// locates it, resolves which work item it belongs to, and publishes evidence.

import { createClient, requireEnv } from "../runtime/http.mjs"
import { FINGERPRINT_TAG, PIPELINE_TAG, readMarker } from "../../../runtime/work-request.mjs"
import { readFileSync } from "node:fs"

const CONFIG = {
  apiVersion: "2022-11-28",
  commentMode: "comment",
  labels: ["agentic"],
  pipelineId: "code-scanning-remediation",
  sourceId: "github-code-scanning",
}

const repository = requireEnv("GITHUB_REPOSITORY")

function client() {
  return createClient({
    baseUrl: process.env.GITHUB_API_URL || "https://api.github.com",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${requireEnv("AGENTIC_GITHUB_TOKEN")}`,
      "X-GitHub-Api-Version": CONFIG.apiVersion,
    },
  })
}

function eventPayload() {
  const path = process.env.GITHUB_EVENT_PATH
  if (!path) return null
  try {
    return JSON.parse(readFileSync(path, "utf8"))
  } catch {
    return null
  }
}

/**
 * The work item is resolved from the pull request body, so evidence is tied to
 * the finding rather than guessed from the branch name.
 */
async function resolveMarkers(pullRequest) {
  if (CONFIG.labels.length === 0) {
    throw new Error("work request labels must not be empty; labels are required for safe deduplication")
  }

  const referenced = /\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)\b/i.exec(
    pullRequest.body || "",
  )
  const direct = readMarker(pullRequest.body, FINGERPRINT_TAG)
  const directPipeline = readMarker(pullRequest.body, PIPELINE_TAG)

  if (!referenced && validFingerprint(direct)) {
    const trusted = await findWorkItem(direct)
    if (trusted) {
      return {
        fingerprint: direct,
        pipeline: readMarker(trusted.body, PIPELINE_TAG),
        candidate: true,
        trusted: true,
      }
    }
    return {
      fingerprint: "",
      pipeline: directPipeline || CONFIG.pipelineId,
      candidate: true,
      trusted: false,
    }
  }

  if (!referenced) {
    return {
      fingerprint: "",
      pipeline: directPipeline || (direct ? CONFIG.pipelineId : ""),
      candidate: direct !== "" || directPipeline !== "",
      trusted: false,
    }
  }

  const issue = await client().json(`/repos/${repository}/issues/${referenced[1]}`)
  const issueFingerprint = readMarker(issue.body, FINGERPRINT_TAG)
  const issuePipeline = readMarker(issue.body, PIPELINE_TAG)
  const candidate = direct !== "" || directPipeline !== "" || issueFingerprint !== "" || issuePipeline !== ""
  if (
    issue.pull_request ||
    String(issue.number || referenced[1]) !== referenced[1] ||
    issue.state !== "open"
  ) {
    return {
      fingerprint: "",
      pipeline: directPipeline || issuePipeline || (candidate ? CONFIG.pipelineId : ""),
      candidate,
      trusted: false,
    }
  }

  const labels = Array.isArray(issue.labels)
    ? issue.labels.map((label) => (typeof label === "string" ? label : label.name))
    : []
  if (
    CONFIG.labels.length > 0 &&
    !CONFIG.labels.every((label) => labels.some((item) => String(item || "") === label))
  ) {
    return {
      fingerprint: "",
      pipeline: directPipeline || issuePipeline || (candidate ? CONFIG.pipelineId : ""),
      candidate,
      trusted: false,
    }
  }

  const fingerprint = issueFingerprint
  const pipeline = issuePipeline
  const markersMatch =
    (direct === "" || direct === fingerprint) &&
    (directPipeline === "" || directPipeline === pipeline)
  return {
    fingerprint,
    pipeline: pipeline || (candidate ? CONFIG.pipelineId : ""),
    candidate,
    trusted: markersMatch && validFingerprint(fingerprint) && pipeline === CONFIG.pipelineId,
  }
}

async function findWorkItem(fingerprint) {
  if (CONFIG.labels.length === 0) {
    throw new Error("work request labels must not be empty; labels are required for safe deduplication")
  }

  const api = client()

  for (let page = 1; ; page += 1) {
    const query = new URLSearchParams({
      state: "all",
      ...(CONFIG.labels.length > 0 ? { labels: CONFIG.labels.join(",") } : {}),
      per_page: "100",
      page: String(page),
    })
    const items = await api.json(`/repos/${repository}/issues?${query.toString()}`)
    if (!Array.isArray(items)) throw new Error("GitHub issues response was not an array")
    if (items.length === 0) return null

    const item = items.find((candidate) => {
      if (candidate.pull_request || candidate.state !== "open") return false
      const labels = Array.isArray(candidate.labels)
        ? candidate.labels.map((label) => (typeof label === "string" ? label : label.name))
        : []
      return (
        CONFIG.labels.every((label) => labels.some((value) => String(value || "") === label)) &&
        readMarker(candidate.body, FINGERPRINT_TAG) === fingerprint &&
        readMarker(candidate.body, PIPELINE_TAG) === CONFIG.pipelineId
      )
    })
    if (item) return item
    if (items.length < 100) return null
  }
}

function validFingerprint(value) {
  if (CONFIG.sourceId === "github-code-scanning") {
    const prefix = `${CONFIG.sourceId}:${repository}:alert:`
    return value.startsWith(prefix) && /^\d+$/.test(value.slice(prefix.length))
  }

  return value.startsWith(`${CONFIG.sourceId}:`) && !/[\s<>]/.test(value)
}

function isOwnedEvidenceComment(item) {
  return item && item.user && item.user.login === "github-actions[bot]"
}

export async function locateChange() {
  const event = eventPayload()
  const eventPullRequest = event && event.pull_request
  if (!eventPullRequest) return null

  // Re-read the PR so file, finding and check evidence all refer to the same
  // revision rather than mixing the webhook snapshot with later API state.
  const pullRequest = await client().json(
    `/repos/${repository}/pulls/${eventPullRequest.number}`,
  )
  if (!pullRequest) throw new Error("pull request could not be loaded for the evidence event")
  if (pullRequest.state && pullRequest.state !== "open") {
    throw new Error("pull request is no longer open; evidence is stale")
  }
  if (
    eventPullRequest.head &&
    eventPullRequest.head.sha &&
    String(pullRequest.head && pullRequest.head.sha) !== String(eventPullRequest.head.sha)
  ) {
    throw new Error("pull request changed after the checks event; evidence is stale")
  }
  if (
    eventPullRequest.base &&
    eventPullRequest.base.sha &&
    String(pullRequest.base && pullRequest.base.sha) !== String(eventPullRequest.base.sha)
  ) {
    throw new Error("pull request base changed after the checks event; evidence is stale")
  }
  if (
    eventPullRequest.merge_commit_sha &&
    String(pullRequest.merge_commit_sha || "") !== String(eventPullRequest.merge_commit_sha)
  ) {
    throw new Error("pull request merge revision changed after the checks event; evidence is stale")
  }

  const markers = await resolveMarkers(pullRequest)
  if (!markers.candidate) return null
  if (markers.pipeline && markers.pipeline !== CONFIG.pipelineId) return null

  return {
    pullRequest: pullRequest.number,
    ref: pullRequest.head && pullRequest.head.ref,
    headRepository: pullRequest.head && pullRequest.head.repo && pullRequest.head.repo.full_name,
    headSha: (eventPullRequest.head && eventPullRequest.head.sha) || (pullRequest.head && pullRequest.head.sha),
    baseSha: (eventPullRequest.base && eventPullRequest.base.sha) || (pullRequest.base && pullRequest.base.sha),
    baseRef: pullRequest.base && pullRequest.base.ref,
    mergeSha: eventPullRequest.merge_commit_sha || pullRequest.merge_commit_sha || "",
    draft: Boolean(pullRequest.draft),
    body: pullRequest.body || "",
    fingerprint: markers.trusted ? markers.fingerprint : "",
    workItemTrusted: markers.trusted,
    pipeline: markers.pipeline,
  }
}

export async function previousEvidenceCandidate() {
  const event = eventPayload()
  const pullRequest = event && event.pull_request
  const headSha = pullRequest && pullRequest.head && pullRequest.head.sha
  if (!headSha) return null

  const statuses = await client().json(
    `/repos/${repository}/commits/${headSha}/statuses?per_page=100`,
  )
  if (!Array.isArray(statuses)) throw new Error("GitHub commit statuses response was not an array")
  const context = `${CONFIG.pipelineId}-evidence`
  const previous = statuses.find((status) => String(status.context || "") === context)
  if (!previous) return null
  return !String(previous.description || "").startsWith("Not a ")
}

export async function changedPaths(change) {
  const current = await client().json(`/repos/${repository}/pulls/${change.pullRequest}`)
  if (!current || current.state && current.state !== "open") {
    throw new Error("pull request is no longer open")
  }
  if (!change.headSha || String(current.head && current.head.sha) !== String(change.headSha)) {
    throw new Error("pull request changed after the checks event; evidence is stale")
  }
  if (change.baseSha && String(current.base && current.base.sha) !== String(change.baseSha)) {
    throw new Error("pull request base changed after the checks event; evidence is stale")
  }
  if (change.mergeSha && String(current.merge_commit_sha || "") !== String(change.mergeSha)) {
    throw new Error("pull request merge revision changed after the checks event; evidence is stale")
  }

  const files = []

  for (let page = 1; ; page += 1) {
    const batch = await client().json(
      `/repos/${repository}/pulls/${change.pullRequest}/files?per_page=100&page=${page}`
    )
    if (!Array.isArray(batch)) throw new Error("pull request files response was not an array")
    if (batch.length === 0) break
    if (files.length + batch.length >= 3000) {
      throw new Error("pull request file list reached GitHub's 3,000-file limit")
    }
    files.push(
      ...batch.map((file) => {
        if (!file || typeof file.filename !== "string" || typeof file.status !== "string") {
          throw new Error("pull request files response contained an invalid file")
        }
        return {
          path: file.filename,
          previousPath: file.previous_filename ? String(file.previous_filename) : "",
          status: file.status,
          additions: Number(file.additions || 0),
          deletions: Number(file.deletions || 0),
        }
      }),
    )
    if (batch.length < 100) break
  }

  return files
}

export async function comment(change, body) {
  if (CONFIG.commentMode === "log-only") {
    console.log("evidenceCommentMode is log-only; not posting a comment.")
    return
  }

  const evidenceKey =
    change.fingerprint || `unlinked-pr:${CONFIG.pipelineId}:${change.pullRequest}`
  const marker = `<!-- agentic-evidence-for: ${evidenceKey} -->`
  const content = body.includes(marker) ? body : `${body}\n\n${marker}`
  const api = client()

  const current = await api.json(`/repos/${repository}/pulls/${change.pullRequest}`)
  if (!current) throw new Error("pull request could not be loaded for evidence publication")
  if (current.state && current.state !== "open") {
    throw new Error("pull request is no longer open; evidence is stale")
  }
  if (
    process.env.AGENTIC_EVENT_HEAD_SHA &&
    String(current.head && current.head.sha) !== String(process.env.AGENTIC_EVENT_HEAD_SHA)
  ) {
    throw new Error("pull request changed after the checks event; evidence is stale")
  }
  if (change.headSha && String(current.head && current.head.sha) !== String(change.headSha)) {
    throw new Error("pull request changed after the checks event; evidence is stale")
  }
  if (change.baseSha && String(current.base && current.base.sha) !== String(change.baseSha)) {
    throw new Error("pull request base changed after the checks event; evidence is stale")
  }
  if (change.mergeSha && String(current.merge_commit_sha || "") !== String(change.mergeSha)) {
    throw new Error("pull request merge revision changed after the checks event; evidence is stale")
  }

  for (let page = 1; ; page += 1) {
    const comments = await api.json(
      `/repos/${repository}/issues/${change.pullRequest}/comments?per_page=100&page=${page}`,
    )
    if (!Array.isArray(comments)) throw new Error("pull request comments response was not an array")
    if (comments.length === 0) break

    const existing = comments.find(
      (item) => String(item.body || "").includes(marker) && isOwnedEvidenceComment(item),
    )
    if (existing) {
      await api.json(`/repos/${repository}/issues/comments/${existing.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ body: content }),
      })
      return
    }
    if (comments.length < 100) break
  }

  await api.json(`/repos/${repository}/issues/${change.pullRequest}/comments`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ body: content }),
  })
}
