// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Execution seam, delegated. This adapter does not run an agent; it describes
// how the work item should trigger one. Keeping that here rather than inside
// the work-item adapter is what lets a region swap either side independently.

const CONFIG = {
  mode: "copilot-agent",
  assignees: ["copilot-swe-agent[bot]"],
  model: "gpt-5.6-luna",
}

export const MODE = CONFIG.mode

export function describe(request) {
  const directive = { assignees: CONFIG.assignees, payloadExtras: {} }

  // Preview API shape, isolated so a repository without agent access can still
  // use this adapter via workRequestMode: plain-issue.
  if (CONFIG.mode === "copilot-agent") {
    directive.payloadExtras.agent_assignment = {
      target_repo: request.repository,
      base_branch: request.baseBranch,
      custom_instructions: request.instructions,
    }
    if (CONFIG.model) directive.payloadExtras.agent_assignment.model = CONFIG.model
  }

  return directive
}
