// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Source seam for GitHub Code Scanning.
//
// Guarantees: it never dismisses, closes or otherwise writes to an alert, and
// `reverify` requires a completed analysis for the PR head before checking the
// finding set, so "the finding is gone" is a fact rather than an inference.

import { createClient, log, requireEnv } from "../runtime/http.mjs"
import { fingerprint } from "../../../runtime/work-request.mjs"
import { ineligibleReason } from "../runtime/policy.mjs"

export const SOURCE = "github-code-scanning"

const CONFIG = {
  alertState: "open",
  pageSize: 100,
  maxPerRun: 20,
  maxDescriptionChars: 55000,
  apiVersion: "2022-11-28",
  scannerWaitSeconds: 300,
  scannerPollSeconds: 10,
  baseBranch: "main",
  instructions: "Fix the finding referenced above in this repository, against the\n`main` branch.\n- Change only what the finding requires.\n- Add or update a test that covers the fixed behaviour.\n- Run the repository's lint, test and build commands.\n- Use the highest reasoning level available for the selected model.\n- Open a draft pull request whose title contains the finding reference.\n- Link the governed work item in the pull request description with\n  `Fixes #<work-item-number>`.\n- Copy the hidden `agentic-fingerprint` and `agentic-pipeline` markers from\n  the work item into the pull request description unchanged. They are used\n  to classify the pull request before repository code may execute.\n- In the draft pull request description, use these headings and fill them:\n  `## Confidence` with `Level: low|medium|high` and its basis, `## Checks`\n  with the checks run, `## Assumptions`, and `## Residual risk`.\n  The machine-checked evidence comment is authoritative.\n- Do not dismiss, close or suppress the finding.\n- Do not merge the pull request or deploy changes.\n",
  labels: ["agentic"],
  titleFormat: "[code-scanning {alertNumber}] {rule}",
}

const repository = requireEnv("GITHUB_REPOSITORY")

function configuredBranch() {
  return CONFIG.baseBranch.startsWith("refs/heads/")
    ? CONFIG.baseBranch.slice("refs/heads/".length)
    : CONFIG.baseBranch
}

function configuredRef() {
  return CONFIG.baseBranch.startsWith("refs/")
    ? CONFIG.baseBranch
    : `refs/heads/${CONFIG.baseBranch}`
}

function client() {
  return createClient({
    baseUrl: process.env.GITHUB_API_URL || "https://api.github.com",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${requireEnv("AGENTIC_GITHUB_TOKEN")}`,
      "X-GitHub-Api-Version": CONFIG.apiVersion,
    },
  })
}

async function listAlerts(query) {
  const api = client()
  const alerts = []

  for (let page = 1; ; page += 1) {
    const search = new URLSearchParams({ ...query, per_page: String(CONFIG.pageSize), page: String(page) })
    const response = await api.request(`/repos/${repository}/code-scanning/alerts?${search.toString()}`)

    if (response.status === 403) {
      throw new Error(
        "Code scanning alerts are not readable: enable code scanning for this " +
          "repository and grant the token security-events read access."
      )
    }
    if (!response.ok) {
      throw new Error(`Failed to list code scanning alerts: ${response.status} ${await response.text()}`)
    }

    const batch = await response.json()
    if (!Array.isArray(batch)) {
      throw new Error("Code scanning alerts response was not an array")
    }
    if (batch.length === 0) break
    alerts.push(...batch)
    if (batch.length < CONFIG.pageSize) break
  }

  return alerts
}

async function listAnalyses(query) {
  const api = client()
  const analyses = []

  for (let page = 1; ; page += 1) {
    const search = new URLSearchParams({ ...query, per_page: String(CONFIG.pageSize), page: String(page) })
    const response = await api.request(`/repos/${repository}/code-scanning/analyses?${search.toString()}`)

    if (response.status === 403) {
      throw new Error(
        "Code scanning analyses are not readable: enable code scanning for this " +
          "repository and grant the token security-events read access."
      )
    }
    if (!response.ok) {
      throw new Error(`Failed to list code scanning analyses: ${response.status} ${await response.text()}`)
    }

    const batch = await response.json()
    if (!Array.isArray(batch)) {
      throw new Error("Code scanning analyses response was not an array")
    }
    if (batch.length === 0) break
    analyses.push(...batch)
    if (batch.length < CONFIG.pageSize) break
  }

  return analyses
}

async function getAlert(number) {
  const expectedRef = configuredRef()
  const branchAlerts = await listAlerts({ ref: expectedRef })
  const branchAlert = branchAlerts.find((alert) => String(alert.number) === String(number))

  const response = await client().request(`/repos/${repository}/code-scanning/alerts/${number}`)
  if (response.status === 404) return null
  if (response.status === 403) {
    throw new Error(
      "Code scanning alerts are not readable: enable code scanning for this " +
        "repository and grant the token security-events read access."
    )
  }
  if (!response.ok) {
    throw new Error(`Failed to get code scanning alert ${number}: ${response.status} ${await response.text()}`)
  }
  const payload = await response.json()
  if (!branchAlert && String(payload.most_recent_instance && payload.most_recent_instance.ref || "") !== expectedRef) {
    return null
  }
  if (!branchAlert) return payload

  // The list endpoint supplies the configured branch instance, while only the
  // detail endpoint supplies linked_pull_requests. Preserve both facts.
  return {
    ...payload,
    ...branchAlert,
    linked_pull_requests: payload.linked_pull_requests,
    most_recent_instance: branchAlert.most_recent_instance || payload.most_recent_instance,
  }
}

async function currentPullRequest(number) {
  const response = await client().json(`/repos/${repository}/pulls/${number}`)
  return response && response.state === "open" ? response : null
}

function eventRevision(name, fallback) {
  return process.env[name] || fallback || ""
}

function sleep(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds))
}

function scannerResult(analyses, headSha, mergeSha, pullRequest, expectedTool, expectedCategory) {
  const expectedRevisions = new Map(
    [
      [`refs/pull/${pullRequest}/head`, String(headSha || "")],
      [`refs/pull/${pullRequest}/merge`, String(mergeSha || "")],
    ].filter(([, sha]) => sha !== ""),
  )
  if (expectedRevisions.size === 0) {
    return {
      status: "fail",
      detail: "no current pull request revision was available",
      retryable: false,
    }
  }

  if (analyses.length === 0) {
    return {
      status: "fail",
      detail: "no completed code scanning analysis was found for this pull request",
      retryable: true,
    }
  }

  const category = String(expectedCategory || "").trim()
  if (category === "") {
    return {
      status: "fail",
      detail: "originating finding did not identify a scanner category",
      retryable: false,
    }
  }

  const matching = analyses.filter(
    (analysis) =>
      expectedRevisions.has(String(analysis.ref || "")) &&
      expectedRevisions.get(String(analysis.ref || "")) === String(analysis.commit_sha || "") &&
      String((analysis.tool && analysis.tool.name) || "").toLowerCase() === expectedTool.toLowerCase() &&
      String(analysis.category || analysis.analysis_key || "").trim() === category,
  )
  if (matching.length === 0) {
    return {
      status: "fail",
      detail: "no code scanning analysis was found for the current pull request revision",
      retryable: true,
    }
  }

  const latest = [...matching].sort((left, right) => {
    const leftTime = Date.parse(String(left.created_at || "")) || 0
    const rightTime = Date.parse(String(right.created_at || "")) || 0
    return rightTime - leftTime
  })[0] || {}
  // The analyses endpoint lists completed analyses. Some compatible providers
  // expose a status field as well, so honour it when present.
  const status = String(latest.status || "").toLowerCase()
  const complete =
    status === "" || ["complete", "completed", "pass", "passed", "success", "succeeded"].includes(status)
  const error = String(latest.error || "").trim()
  const warning = String(latest.warning || "").trim()

  if (!complete || error || warning) {
    return {
      status: "fail",
      detail: `code scanning analysis is not complete (${status || "unknown"}${
        error ? `, ${error}` : ""
      })${warning ? `; provider warning: ${warning}` : ""}`,
      retryable: !error && !warning && ["in_progress", "pending", "queued"].includes(status),
    }
  }

  return {
    status: "pass",
    detail: `code scanning analysis completed for ${latest.commit_sha || "the pull request"}`,
    retryable: false,
  }
}

async function waitForScannerAnalysis({ pullRequest, headSha, mergeSha, tool, category }) {
  const waitMilliseconds = CONFIG.scannerWaitSeconds * 1000
  const pollMilliseconds = CONFIG.scannerPollSeconds * 1000
  const deadline = Date.now() + waitMilliseconds

  for (;;) {
    const analyses = await listAnalyses({ pr: String(pullRequest) })
    const result = scannerResult(analyses, headSha, mergeSha, pullRequest, tool, category)
    if (result.status === "pass" || !result.retryable || Date.now() >= deadline) {
      return result
    }

    const delay = Math.min(pollMilliseconds, deadline - Date.now())
    if (delay <= 0) return result
    log(`Waiting for code scanning analysis for pull request ${pullRequest}`)
    await sleep(delay)
  }
}

function candidateOf(alert) {
  const rule = alert.rule || {}
  const instance = alert.most_recent_instance || {}
  const location = instance.location || {}

  return {
    ruleId: rule.id || "",
    tool: (alert.tool && alert.tool.name) || "",
    securitySeverity: rule.security_severity_level || "",
    ruleSeverity: rule.severity || "",
    path: location.path || "",
    classifications: instance.classifications || [],
  }
}

function toWorkRequest(alert) {
  const rule = alert.rule || {}
  const tool = alert.tool || {}
  const instance = alert.most_recent_instance || {}
  const location = instance.location || {}
  const path = location.path || ""

  const message = (instance.message && instance.message.text) || rule.description || ""
  const guidance = rule.help || rule.full_description || ""
  const description =
    [message, guidance].filter(Boolean).join("\n\n").slice(0, CONFIG.maxDescriptionChars) ||
    "No description provided."

  return {
    source: SOURCE,
    sourceId: String(alert.number),
    url: alert.html_url,
    fingerprint: fingerprint(SOURCE, repository, `alert:${alert.number}`),
    // Not the deduplication key. Recorded so a future adapter can correlate the
    // same finding reported by another scanner.
    correlation: `${rule.id || rule.name || "unknown-rule"}@${path || "unknown-path"}`,
    workType: "security-remediation",
    reference: `alert ${alert.number}`,
    title: CONFIG.titleFormat
      .replace("{alertNumber}", String(alert.number))
      .replace("{rule}", rule.name || rule.id || "code scanning finding")
      .replace("{path}", path),
    rule: { id: rule.id || "", name: rule.name || "", severity: rule.severity || "" },
    tool: { name: tool.name || "", version: tool.version || "" },
    securitySeverity: rule.security_severity_level || "",
    classifications: instance.classifications || [],
    location: { path, startLine: location.start_line || null, endLine: location.end_line || null },
    commitSha: instance.commit_sha || "",
    ref: instance.ref || "",
    description,
    repository,
    baseBranch: CONFIG.baseBranch,
    labels: CONFIG.labels,
    instructions: CONFIG.instructions,
  }
}

export async function discover() {
  const ref = CONFIG.baseBranch.startsWith("refs/")
    ? CONFIG.baseBranch
    : `refs/heads/${CONFIG.baseBranch}`
  const alerts = await listAlerts({ state: CONFIG.alertState, ref })
  log(`Fetched ${alerts.length} alert(s) in state '${CONFIG.alertState}'`)

  const eligible = []
  for (const alert of alerts) {
    const reason = ineligibleReason(candidateOf(alert))
    if (reason !== null) {
      log(`alert ${alert.number}: skipped, ${reason}`)
      continue
    }
    eligible.push(alert)
  }

  return eligible.slice(0, CONFIG.maxPerRun).map(toWorkRequest)
}

/**
 * Re-verification is the assertion that makes a remediation trustworthy: the
 * source confirms the work item, analysis and complete pull-request finding set,
 * so a fix that only looks right in the diff still fails.
 */
export async function reverify({ fingerprint: value, pullRequest, headSha, baseSha, mergeSha }) {
  value = String(value || "")
  const prefix = `${SOURCE}:${repository}:alert:`
  if (!value.startsWith(prefix) || !/^\d+$/.test(value.slice(prefix.length))) {
    return {
      status: "fail",
      detail: `fingerprint ${value} is not a valid ${SOURCE} finding identity`,
      scanner: { status: "fail", detail: "invalid finding identity" },
      newFindings: null,
    }
  }
  if (!pullRequest) {
    return {
      status: "fail",
      detail: "no pull request number was available",
      scanner: { status: "fail", detail: "no pull request number was available" },
      newFindings: null,
    }
  }

  const current = await currentPullRequest(pullRequest)
  if (!current) {
    return {
      status: "fail",
      detail: "pull request is no longer open",
      scanner: { status: "fail", detail: "pull request is no longer open" },
      newFindings: null,
    }
  }
  const configuredBaseRef = configuredBranch()
  if (String(current.base && current.base.ref || "") !== configuredBaseRef) {
    return {
      status: "fail",
      detail: `pull request targets ${current.base && current.base.ref || "an unknown branch"}, not ${configuredBaseRef}`,
      scanner: { status: "fail", detail: "pull request target branch is outside the configured scope" },
      newFindings: null,
    }
  }
  const expectedHeadSha = eventRevision("AGENTIC_EVENT_HEAD_SHA", headSha)
  const expectedBaseSha = eventRevision("AGENTIC_EVENT_BASE_SHA", baseSha)
  const expectedMergeSha = eventRevision("AGENTIC_EVENT_MERGE_SHA", mergeSha)
  if (!expectedHeadSha || String(current.head && current.head.sha || "") !== String(expectedHeadSha)) {
    return {
      status: "fail",
      detail: "pull request changed after the checks event; evidence is stale",
      scanner: { status: "fail", detail: "pull request head changed during verification" },
      newFindings: null,
    }
  }
  if (expectedBaseSha && String(current.base && current.base.sha || "") !== String(expectedBaseSha)) {
    return {
      status: "fail",
      detail: "pull request base changed after the checks event; evidence is stale",
      scanner: { status: "fail", detail: "pull request base changed during verification" },
      newFindings: null,
    }
  }
  if (expectedMergeSha && String(current.merge_commit_sha || "") !== String(expectedMergeSha)) {
    return {
      status: "fail",
      detail: "pull request merge revision changed after the checks event; evidence is stale",
      scanner: { status: "fail", detail: "pull request merge revision changed during verification" },
      newFindings: null,
    }
  }

  const number = value.slice(prefix.length)
  const original = await getAlert(number)
  if (!original || String(original.number) !== number) {
    return {
      status: "fail",
      detail: `originating alert ${number} could not be verified in this repository`,
      scanner: { status: "fail", detail: "originating alert identity was not found" },
      newFindings: null,
    }
  }
  if (["dismissed", "fixed"].includes(String(original.state || "").toLowerCase())) {
    return {
      status: "fail",
      detail: `originating alert ${number} was ${String(original.state).toLowerCase()} instead of fixed by this pull request`,
      scanner: {
        status: "fail",
        detail: `originating alert was ${String(original.state).toLowerCase()}`,
      },
      newFindings: null,
    }
  }
  const linkedPullRequests = Array.isArray(original.linked_pull_requests)
    ? original.linked_pull_requests
    : []
  if (!linkedPullRequests.some((item) => Number(item.number) === Number(pullRequest))) {
    return {
      status: "fail",
      detail: `originating alert ${number} is not linked to pull request ${pullRequest}`,
      scanner: { status: "fail", detail: "originating alert is not linked to this pull request" },
      newFindings: null,
    }
  }

  const instance = original.most_recent_instance || {}
  const scanner = await waitForScannerAnalysis({
    pullRequest,
    headSha: expectedHeadSha,
    mergeSha: expectedMergeSha,
    tool: String((original.tool && original.tool.name) || ""),
    category: instance.category || instance.analysis_key,
  })
  if (scanner.status !== "pass") {
    return {
      status: "fail",
      detail: scanner.detail,
      scanner,
      newFindings: null,
    }
  }

  const alerts = await listAlerts({ state: "open", pr: String(pullRequest) })
  const stillOpen = alerts.some((alert) => String(alert.number) === number)
  const expectedTool = String((original.tool && original.tool.name) || "").toLowerCase()
  const expectedCategory = String(instance.category || instance.analysis_key || "")
  const newFindings = alerts
    .filter((alert) => {
      const alertInstance = alert.most_recent_instance || {}
      return (
        String((alert.tool && alert.tool.name) || "").toLowerCase() === expectedTool &&
        String(alertInstance.category || alertInstance.analysis_key || "") === expectedCategory
      )
    })
    .filter((alert) => String(alert.number) !== number)
    .map((alert) => String(alert.number))

  return {
    status: stillOpen ? "fail" : "pass",
    detail: stillOpen
      ? `alert ${number} is still open on this pull request`
      : `alert ${number} is no longer reported for this pull request`,
    scanner,
    newFindings,
  }
}
