// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Validation seam.
//
// Every entry in the evidence table is produced by running something or asking
// a provider. Nothing here accepts a narrative claim, which is the point: a
// reviewer who trusts prose stops reading it within a fortnight.

import { loadAdapter } from "../../../runtime/adapter-loader.mjs"
import {
  assertion,
  confidence,
  decision,
  formatComment,
  looksLikeTest,
  protectedPathViolations,
  REQUIRE_TEST_FOR_TOUCHED_CODE,
} from "../runtime/evidence.mjs"

const ENTRYPOINTS = {"source":"./pipelines/code-scanning-remediation/adapters/source.mjs","workItem":"./pipelines/code-scanning-remediation/adapters/work-item.mjs","execution":"./pipelines/code-scanning-remediation/adapters/execution.mjs","delivery":"./pipelines/code-scanning-remediation/adapters/delivery.mjs","validation":"./pipelines/code-scanning-remediation/adapters/validation.mjs"}

const CONFIG = {
  // Falls back to the commands the repository already declares, so validation
  // does not become a second place to describe how this project is built.
  commands: ["echo"],
}

function stripNoise(text) {
  // Explicit linear scan rather than a regex .replace(): jumps straight from
  // an opening delimiter to just past its matching close (or to the end, if
  // unterminated), so there is no span to remove and nothing that can rejoin
  // into a new match (CodeQL js/incomplete-multi-character-sanitization).
  const DELIMITERS = [
    { open: "<!--", close: "-->" },
    { open: "```", close: "```" },
  ]
  let result = ""
  let index = 0
  outer: while (index < text.length) {
    for (const { open, close } of DELIMITERS) {
      if (text.startsWith(open, index)) {
        const end = text.indexOf(close, index + open.length)
        index = end === -1 ? text.length : end + close.length
        continue outer
      }
    }
    result += text[index]
    index += 1
  }
  return result
}

function sectionContent(text, heading) {
  const pattern = new RegExp(`^#{1,6}\\s+${heading}\\s*$`, "im")
  const match = pattern.exec(text)
  if (!match) return ""

  const remainder = text.slice(match.index + match[0].length)
  const nextHeading = /^#{1,6}\s+/m.exec(remainder)
  const section = nextHeading ? remainder.slice(0, nextHeading.index) : remainder
  return stripNoise(section).trim()
}

function reportGaps(body) {
  const text = String(body || "")
  const gaps = []
  const confidenceSection = sectionContent(text, "Confidence")

  if (!confidenceSection) {
    gaps.push("confidence section")
  } else {
    if (!/^Level:\s*(?:low|medium|high)\s*$/im.test(confidenceSection)) {
      gaps.push("confidence level")
    }
    if (!/^Basis:\s*\S.*$/im.test(confidenceSection)) gaps.push("confidence basis")
  }

  for (const [name, heading] of [
    ["checks", "Checks?"],
    ["assumptions", "Assumptions?"],
    ["residual risk", "Residual\\s+Risk"],
  ]) {
    if (!sectionContent(text, heading)) gaps.push(name)
  }

  return gaps
}

export async function assess(change) {
  const assertions = []

  // 1. The originating finding, re-checked at the source rather than inferred.
  const source = await loadAdapter("source", ENTRYPOINTS.source)
  if (source === null || typeof source.reverify !== "function") {
    assertions.push(
      assertion("finding-resolved", "Originating finding is resolved", "fail", "no source adapter")
    )
    assertions.push(assertion("scanner-analysis", "Scanner analysis completed", "fail", "no source adapter"))
    assertions.push(assertion("no-new-findings", "No new findings were introduced", "fail", "no source adapter"))
  } else if (!change.fingerprint || change.workItemTrusted !== true) {
    assertions.push(
      assertion(
        "finding-resolved",
        "Originating finding is resolved",
        "skip",
        "this change is not linked to a trusted work item"
      )
    )
    assertions.push(assertion("scanner-analysis", "Scanner analysis completed", "fail", "this change is not linked to a trusted work item"))
    assertions.push(assertion("no-new-findings", "No new findings were introduced", "fail", "this change is not linked to a trusted work item"))
  } else {
    let result
    try {
      result = await source.reverify(change)
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error)
      result = {
        status: "fail",
        detail: `source verification failed: ${detail}`,
        scanner: { status: "fail", detail },
        newFindings: null,
      }
    }
    assertions.push(
      assertion(
        "finding-resolved",
        "Originating finding is resolved",
        result.status === "pass" ? "pass" : "fail",
        result.detail,
      )
    )

    const scanner = result.scanner
    assertions.push(
      assertion(
        "scanner-analysis",
        "Scanner analysis completed",
        scanner && scanner.status === "pass" ? "pass" : "fail",
        scanner ? scanner.detail : "source did not report scanner completion",
      )
    )

    const newFindings = result.newFindings
    assertions.push(
      assertion(
        "no-new-findings",
        "No new findings were introduced",
        Array.isArray(newFindings) && newFindings.length === 0 ? "pass" : "fail",
        Array.isArray(newFindings)
          ? newFindings.length === 0
            ? "no additional findings were reported"
            : `new finding(s): ${newFindings.slice(0, 20).join(", ")}`
          : "source did not report the complete pull-request finding set",
      )
    )
  }

  // 2. Repository commands. The host runs these in a separate unprivileged job;
  // this trusted provider-verification process only consumes that job result.
  if (CONFIG.commands.length === 0) {
    assertions.push(assertion("commands", "Repository checks pass", "skip", "no commands configured"))
  } else {
    const result = process.env.AGENTIC_CHECKS_RESULT
    const passed = result === "success"
    assertions.push(
      assertion(
        "commands",
        "Repository checks pass",
        passed ? "pass" : "fail",
        passed
          ? "unprivileged checks job passed"
          : result
            ? `unprivileged checks job: ${result}`
            : "unprivileged checks job result was not provided",
      ),
    )
  }

  // 3. Blast radius: protected paths and test coverage of what was touched.
  const delivery = await loadAdapter("delivery", ENTRYPOINTS.delivery)
  if (delivery === null || typeof delivery.changedPaths !== "function") {
    assertions.push(assertion("scope", "Change stays inside its scope", "fail", "no delivery adapter"))
  } else {
    let files
    let fileListError = ""
    try {
      files = await delivery.changedPaths(change)
    } catch (error) {
      fileListError = error instanceof Error ? error.message : String(error)
      files = []
    }

    const validFiles =
      Array.isArray(files) &&
      files.every(
        (file) =>
          file &&
          typeof file === "object" &&
          typeof file.path === "string" &&
          typeof file.status === "string",
      )
    const normalizedFiles = validFiles ? files : []
    const paths = normalizedFiles.map((file) => file.path)
    const previousPaths = normalizedFiles
      .map((file) => file.previousPath)
      .filter((path) => typeof path === "string" && path.length > 0)
    const violations = [
      ...new Set([...protectedPathViolations(paths), ...protectedPathViolations(previousPaths)]),
    ]

    assertions.push(
      assertion(
        "protected-paths",
        "No protected path was modified",
        violations.length === 0 ? "pass" : "fail",
        violations.length === 0 ? `${paths.length} file(s) changed` : violations.join(", ")
      )
    )

    if (fileListError || !validFiles) {
      assertions.push(
        assertion(
          "file-list",
          "Pull request file list is complete",
          "fail",
          fileListError || "delivery returned an invalid file list",
        ),
      )
    }

    const touchedTests = [...new Set([...paths, ...previousPaths])].filter(looksLikeTest)
    const status = touchedTests.length > 0 ? "pass" : REQUIRE_TEST_FOR_TOUCHED_CODE ? "fail" : "skip"
    assertions.push(
      assertion(
        "tests-touched",
        "Change carries a test",
        status,
        touchedTests.length > 0 ? touchedTests.join(", ") : "no test file was changed"
      )
    )

    const deletedTests = normalizedFiles
      .filter((file) => {
        const status = file.status.toLowerCase()
        const destinationIsTest = looksLikeTest(file.path)
        const previousIsTest = looksLikeTest(file.previousPath || "")
        return (
          ["removed", "deleted"].includes(status) && destinationIsTest ||
          status === "renamed" && previousIsTest && !destinationIsTest
        )
      })
      .flatMap((file) => [file.path, file.previousPath || ""])
      .filter((path) => path.length > 0 && looksLikeTest(path))
    assertions.push(
      assertion(
        "tests-deleted",
        "No test file was deleted",
        deletedTests.length === 0 ? "pass" : "fail",
        deletedTests.length === 0 ? "no test files were deleted" : deletedTests.join(", "),
      )
    )
  }

  // 4. The change is still a draft, i.e. nobody has been asked to merge yet.
  assertions.push(
    assertion(
      "draft",
      "Pull request is a draft",
      change.draft ? "pass" : "skip",
      change.draft ? "awaiting human review" : "already marked ready for review"
    )
  )

  const gaps = reportGaps(change.body)
  assertions.push(
    assertion(
      "agent-report",
      "Pull request includes the agent report",
      gaps.length === 0 ? "pass" : "fail",
      gaps.length === 0 ? "confidence, checks, assumptions and residual risk are reported" : `missing ${gaps.join(", ")}`
    )
  )

  const level = confidence(assertions)
  const outcome = decision(assertions)
  return {
    assertions,
    confidence: level,
    decision: outcome,
    blocking: outcome.status === "blocked",
    blockers: outcome.blockers,
    body: formatComment({
      assertions,
      confidence: level,
      decision: outcome,
      fingerprint: change.fingerprint,
    }),
  }
}
