// Generated by agentic. Edit .agentic/config.yaml and run `agentic update`.
//
// Work-item seam for GitHub Issues.

import { createClient, requireEnv } from "../runtime/http.mjs"
import { CORRELATION_TAG, FINGERPRINT_TAG, PIPELINE_TAG, readMarker, writeMarker } from "../../../runtime/work-request.mjs"

export const MAX_OPEN_WORK_REQUESTS = 5

const CONFIG = {
  labels: ["agentic"],
  apiVersion: "2022-11-28",
  pipelineId: "code-scanning-remediation",
}

const repository = requireEnv("GITHUB_REPOSITORY")

function client() {
  return createClient({
    baseUrl: process.env.GITHUB_API_URL || "https://api.github.com",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${requireEnv("AGENTIC_GITHUB_TOKEN")}`,
      "X-GitHub-Api-Version": CONFIG.apiVersion,
    },
  })
}

/**
 * The issues endpoint is used rather than the search API because search is
 * eventually consistent and would let a duplicate through.
 */
export async function findExisting({ sources = [] } = {}) {
  const fingerprints = new Set()
  let openCount = 0

  if (CONFIG.labels.length === 0) {
    throw new Error("work request labels must not be empty; labels are required for safe deduplication")
  }

  const api = client()
  for (let page = 1; ; page += 1) {
    const query = new URLSearchParams({
      state: "all",
      labels: CONFIG.labels.join(","),
      per_page: "100",
      page: String(page),
    })

    const batch = await api.json(`/repos/${repository}/issues?${query.toString()}`)
    if (!Array.isArray(batch)) throw new Error("GitHub issues response was not an array")
    if (batch.length === 0) break

    for (const item of batch) {
      if (item.pull_request) continue
      const marker = readMarker(item.body, FINGERPRINT_TAG)
      const pipeline = readMarker(item.body, PIPELINE_TAG)
      if (pipeline && pipeline !== CONFIG.pipelineId) continue
      if (!pipeline && sources.length > 0 && !sources.some((source) => marker.startsWith(`${source}:`))) {
        continue
      }
      if (item.state === "open") {
        if (marker) fingerprints.add(marker)
        openCount += 1
      }
    }

    if (batch.length < 100) break
  }

  return { fingerprints, openCount }
}

function renderBody(request) {
  const location = request.location
    ? request.location.startLine
      ? `${request.location.path}:${request.location.startLine}`
      : request.location.path
    : ""

  return [
    `Source finding: ${request.url}`,
    "",
    request.rule ? `- Rule: \`${request.rule.id}\` ${request.rule.name}`.trim() : "",
    request.tool ? `- Tool: ${request.tool.name} ${request.tool.version}`.trim() : "",
    `- Severity: ${request.securitySeverity || (request.rule && request.rule.severity) || "unknown"}`,
    location ? `- Location: ${location}` : "",
    request.commitSha ? `- Commit: ${request.commitSha}` : "",
    "",
    request.description,
    "",
    "## Agent instructions",
    "",
    request.instructions,
    "",
    writeMarker(FINGERPRINT_TAG, request.fingerprint),
    writeMarker(PIPELINE_TAG, request.pipeline || CONFIG.pipelineId),
    request.correlation ? writeMarker(CORRELATION_TAG, request.correlation) : "",
  ]
    .filter((line) => line !== "")
    .join("\n")
}

export async function create(request, directive) {
  const payload = {
    title: request.title,
    body: renderBody(request),
    labels: CONFIG.labels,
    assignees: (directive && directive.assignees) || [],
    ...((directive && directive.payloadExtras) || {}),
  }

  const created = await client().json(`/repos/${repository}/issues`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  })

  return { url: created.html_url, id: created.number }
}
